---
title: "Get Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r packagesandsetup}
rm(list=ls())
setwd("~/Desktop/CurrentProjects/LHSproject/Rmd/")

library(Rcompadre)
library(popbio)
library(tidyverse)
library(lme4)
library(demogR)
library(matrixcalc)
library(corrplot)
# library(ggraph)
# library(ggbiplot)
library(ggfortify)

```

# Bring in Compadre DB and filter
```{r fetchcompadre}

#  Fetch most recent database
compadrefull <- cdb_fetch("compadre") %>% 
  cdb_flag() # Flag incomplete entries

# Remove incomplete entries
compadredb <- compadrefull %>% 
  filter(check_NA_A==FALSE & check_NA_U==FALSE & check_singular_U==FALSE) %>% # Remove entries without full mat or survival mat
  filter(!is.na(Altitude)) %>%  # Remove entries with missing elevation 
  filter(OrganismType=='Herbaceous perennial') %>% # only keep herbaceous perennials
  filter(MatrixTreatment=="Unmanipulated"|is.na(MatrixTreatment)) %>% # Only keep matrices without treatments
  filter(MatrixFec=="Yes"|is.na(MatrixFec)) %>% 
  filter(ProjectionInterval==1) %>% # Keep matrices with interval of 1 (year?)
  filter(!is.na(Ecoregion)) %>% # Remove if no ecoregion
  filter(MatrixComposite=='Mean') %>% 
  filter(!is.na(MatrixCriteriaAge))

```


Fix elevation values that are very likely to be in feet, not meters
```{r fixelev, message=FALSE}
compadre_df <- as.data.frame(compadredb)
elev_outliers <- compadre_df %>% filter(Altitude>3000)
hist(compadre_df$Altitude[compadre_df$Altitude>3000],breaks=50)

# Fix two--The original values did't seem to be in meters or feet, but are not in meters
compadredb$Altitude[compadredb$Genus=='Leontopodium'&compadredb$MatrixPopulation=="Arpalle"]=2650
compadredb$Altitude[compadredb$Genus=='Leontopodium'&compadredb$MatrixPopulation=="Dotse"]=2492

rm(elev_outliers)
```


Check for latitude outliers and fix
```{r fixlatitude}
compadre_df <- as.data.frame(compadredb) 
hist(compadre_df$Lat,breaks=50)

## looks fine. Checked that Neg latitudes and country names make sense as well
```


Get list of species names from the subsetted database
```{r elevspplist}

species_list <- as.data.frame(table(compadredb$Genus,compadredb$Species)) %>% 
  filter(Freq>=1)
colnames(species_list)<-c("genus","species","count")

```


Add elevation and latitude to species_list df -- Can use this DF to subset database 
```{r elevdiffilter}

# Elevation info
species_list$min.elev <- NA
species_list$max.elev <- NA

species_list$min.lat <- NA
species_list$max.lat <- NA

for(rowi in 1:nrow(species_list)){

  # Subset to species in rowi
  species_tmp <- subset(compadredb, Genus == species_list$genus[rowi] & Species == species_list$species[rowi])

  species_list$min.elev[rowi] <- min(species_tmp$Altitude, na.rm=T)
  species_list$max.elev[rowi] <- max(species_tmp$Altitude, na.rm=T)

  species_list$min.lat[rowi] <- min(species_tmp$Lat, na.rm=T)
  species_list$max.lat[rowi] <- max(species_tmp$Lat, na.rm=T)
  
}

species_list$elev.diff <- species_list$max.elev-species_list$min.elev
species_list$lat.diff <- abs(species_list$max.lat) - abs(species_list$min.lat)
rm(rowi,species_tmp)

# Can use this to filter for species that have populations occurring at different elevations or latitudes
```


subset database for minimum elevation difference and write output RDS
```{r subsetdbelevdiff}

min_elev_diff=0

# 100 => 26 spp
elev_diff_spp <- species_list %>% 
  filter(count>=3) %>% 
  filter(elev.diff>min_elev_diff)

compadredb_Esub <- compadredb %>% 
  filter(Genus%in%elev_diff_spp$genus&Species%in%elev_diff_spp$species)

saveRDS(compadredb_Esub,paste0("Datasets/elevation_",min_elev_diff,".rds"))

min_lat_diff=0

lat_diff_spp <- species_list %>% 
  filter(lat.diff>min_lat_diff)

compadredb_Lsub <- compadredb %>% 
  filter(Genus%in%lat_diff_spp$genus&Species%in%lat_diff_spp$species)

saveRDS(compadredb_Lsub,paste0("Datasets/latitude_",min_lat_diff,".rds"))


rm(elev_diff_spp,lat_diff_spp,min_elev_diff,min_lat_diff)

```



